environment:

  matrix:
    - PYTHON: "C:\\Miniconda"
      CONDA_PY: "27"
    
    - PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27" 
      ARCH: "64"

    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "34"

    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "34"
      ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%;"

  - conda config --set always_yes true 
  - conda config --add channels omnia 
  - conda install -q conda-build 

build: false # Not a C# project, build stuff at the test step instead.

test_script:
  # run testsuite and upload test results to AppVeyor; return exit code of testsuite
  - conda build -q conda-recipe
