package:
  name: thermotools
  version: !!str dev

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20
    - numpy x.x
    - scipy >=0.11
    - msmtools >=1.1.3

  run:
    - python
    - numpy x.x
    - scipy >=0.11
    - msmtools >=1.1.3

test:
  requires:
    - nose
    - coverage ==4
  imports:
    - thermotools

about:
  home: https://github.com/markovmodel/thermotools
  license: GNU Lesser Public License v3+
  summary: "Lowlevel implementation of free energy estimators"
